services:
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: modernevent-noble-x86_64-image:latest
    container_name: modernevent-noble-x86_64
    command: sleep infinity
    volumes:
      - ../..:/workspace:cached
      - build_dir:/build
volumes:
  build_dir:
    name: modernevent_noble_x86_64_build_dir